# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: h:/private/projects/ECEN302/lab_5/ssd_lab_5/ssd_lab_5.srcs/sources_1/ip/clk_5MHZ/clk_5MHZ.xci
# IP: The module: 'clk_5MHZ' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: h:/private/projects/ECEN302/lab_5/ssd_lab_5/ssd_lab_5.srcs/sources_1/ip/clk_5MHZ/clk_5MHZ_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_5MHZ'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: h:/private/projects/ECEN302/lab_5/ssd_lab_5/ssd_lab_5.srcs/sources_1/ip/clk_5MHZ/clk_5MHZ.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_5MHZ'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: h:/private/projects/ECEN302/lab_5/ssd_lab_5/ssd_lab_5.srcs/sources_1/ip/clk_5MHZ/clk_5MHZ_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_5MHZ'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: h:/private/projects/ECEN302/lab_5/ssd_lab_5/ssd_lab_5.srcs/sources_1/ip/clk_5MHZ/clk_5MHZ.xci
# IP: The module: 'clk_5MHZ' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: h:/private/projects/ECEN302/lab_5/ssd_lab_5/ssd_lab_5.srcs/sources_1/ip/clk_5MHZ/clk_5MHZ_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_5MHZ'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: h:/private/projects/ECEN302/lab_5/ssd_lab_5/ssd_lab_5.srcs/sources_1/ip/clk_5MHZ/clk_5MHZ.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_5MHZ'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: h:/private/projects/ECEN302/lab_5/ssd_lab_5/ssd_lab_5.srcs/sources_1/ip/clk_5MHZ/clk_5MHZ_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_5MHZ'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
