server: server.o
	g++ -o server server.o

server.o: server.cc server.hh
	g++ -c server.cc

client: client.o
	g++ -o client client.o

client.o: client.cc server.hh
	g++ -c client.cc

clean:
	rm -rf *.o server client
