webtalk_init -webtalk_dir H:/private/projects/ECEN302/lab_3/lab_3_2_2/lab_3_2_2.sim/sim_1/behav/xsim/xsim.dir/calc_ones_function_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Aug  6 12:01:51 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2902540" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211337870_1777524719_210723075_765" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "b445c428-fbb8-4b28-a10d-d93c582e924c" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "9ea2df6ff8544248a059a8f65405dc3b" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3592 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "50 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.01_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6356_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1835872904 -regid "211337870_1777524719_210723075_765" -xml H:/private/projects/ECEN302/lab_3/lab_3_2_2/lab_3_2_2.sim/sim_1/behav/xsim/xsim.dir/calc_ones_function_behav/webtalk/usage_statistics_ext_xsim.xml -html H:/private/projects/ECEN302/lab_3/lab_3_2_2/lab_3_2_2.sim/sim_1/behav/xsim/xsim.dir/calc_ones_function_behav/webtalk/usage_statistics_ext_xsim.html -wdm H:/private/projects/ECEN302/lab_3/lab_3_2_2/lab_3_2_2.sim/sim_1/behav/xsim/xsim.dir/calc_ones_function_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
