@echo off
REM ****************************************************************************
REM Vivado (TM) v2020.1 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Fri Sep 11 13:40:32 +1200 2020
REM SW Build 2902540 on Wed May 27 19:54:49 MDT 2020
REM
REM Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
echo "xelab -wto e4bdc4dc15b24c9e8412a03b0a9ea6cc --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot FSM_moore_TB_behav xil_defaultlib.FSM_moore_TB -log elaborate.log"
call xelab  -wto e4bdc4dc15b24c9e8412a03b0a9ea6cc --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot FSM_moore_TB_behav xil_defaultlib.FSM_moore_TB -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
