@echo off
REM ****************************************************************************
REM Vivado (TM) v2020.1 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Thu Aug 06 10:28:44 +1200 2020
REM SW Build 2902540 on Wed May 27 19:54:49 MDT 2020
REM
REM Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
echo "xelab -wto 7d00aa92f012486991a6ce146b64f6c9 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot add_two_values_procedure_tb_behav xil_defaultlib.add_two_values_procedure_tb -log elaborate.log"
call xelab  -wto 7d00aa92f012486991a6ce146b64f6c9 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot add_two_values_procedure_tb_behav xil_defaultlib.add_two_values_procedure_tb -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
